version: "3.9"
services:
    db:
        image: postgres
        volumes:
            - rails6_app_postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: password
        networks:
            - rails6
    web:
        build:
            context: ./docker/rails6
            dockerfile: Dockerfile
        volumes:
            - .:/myapp
            - rails6_app_gems:/usr/local/bundle
        ports:
            - "3000:3000"
        depends_on:
            - db
        networks:
            - rails6

networks:
    rails6:
        driver: bridge

volumes:
    rails6_app_postgres_data:
    rails6_app_gems:
